# template rustfmt configuration
# See: https://rust-lang.github.io/rustfmt/

edition = "2024"

# Line width
max_width = 100
use_small_heuristics = "Default"

reorder_imports = true
reorder_modules = true

# Formatting
newline_style = "Auto"
hard_tabs = false
tab_spaces = 4
